### ISSUE TITLE
fmodulesのバージョンの更新

### ISSUE THREAD

**Issue by y-kanai06** [fierte-product-development/Standard-Library-Extension#2]
pipenv環境を作成した際，fmodulesのバージョンが1.2.2(最新)になるようにpipfile, pipfile.lockを更新する

**Comment by hiro-torii** [comment]
説明不足で申し訳ないです。。。
Polyphenolリポジトリでのpipenv環境の話なので，そちらのpipfle, pipfile.lockを更新してもらえると助かります 🙏

**Comment by y-kanai06** [comment]
申し訳ありません。
Polyphenolリポジトリに上げ直します。
